apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
      - name: hpaimage
        image: hpaimage
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"

